# Generated by Django 2.2.5 on 2020-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('expTime', models.DateTimeField(verbose_name='expected time for completion')),
                ('dueTime', models.DateTimeField(verbose_name='due date')),
            ],
        ),
    ]
