# Generated by Django 2.2.5 on 2020-03-06 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='time when task was added'),
        ),
    ]
