# Generated by Django 3.0.4 on 2020-05-14 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20200305_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='addDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time When Task was Added'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Ex', 'Exercise'), ('Leis', 'Leisure'), ('House', 'Household'), ('Pers', 'Personal'), ('Work', 'Work'), ('', 'None')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(help_text='Enter by when must this task be completed', verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expTime',
            field=models.DurationField(help_text='Enter the amount of time you expect to complete this task', verbose_name='Expected Time for Completion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Task Name'),
        ),
    ]
