# Generated by Django 3.0.4 on 2020-05-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20200514_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Start time of this scheduled instance')),
                ('duration', models.DurationField(verbose_name='Duration of this scheduled instance')),
                ('effective', models.BooleanField(verbose_name='Whether this instance was scheduled effectively')),
            ],
            options={
                'ordering': ['startTime', 'duration', 'effective'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ['addDate', 'dueDate'], 'ordering': ['name', 'category', 'addDate', 'dueDate', 'expTime']},
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Ex', 'Exercise'), ('Leis', 'Leisure'), ('House', 'Household'), ('Pers', 'Personal'), ('Work', 'Work'), ('', 'None')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='times',
            field=models.ManyToManyField(db_table='Scheduled Times', to='planner.ScheduleInstance'),
        ),
    ]
