# Generated by Django 3.0.4 on 2020-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20200514_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ['addDate', 'dueDate'], 'ordering': ['name', 'category', 'user', 'addDate', 'dueDate', 'expTime']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='times',
        ),
        migrations.AddField(
            model_name='task',
            name='times',
            field=models.ManyToManyField(db_table='Scheduled Times', to='planner.ScheduleInstance'),
        ),
    ]
