# Generated by Django 3.0.4 on 2020-05-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20200514_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ['addDate', 'dueDate'], 'ordering': ['name', 'category', 'addDate', 'dueDate', 'expTime']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
