# Generated by Django 3.0.4 on 2020-05-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20200517_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': ['addDate', 'dueDate'], 'ordering': ['addDate', 'dueDate', '-expTime', 'name']},
        ),
    ]
