# Generated by Django 3.0.3 on 2020-05-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20200520_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(help_text='Enter by when must this task be completed in the following format: YYYY-MM-DD HH:MM:SS', verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expTime',
            field=models.DurationField(help_text='Enter the amount of time you expect to need to complete this task in the following format: HH:MM:SS', verbose_name='Expected Time for Completion'),
        ),
    ]
