# Generated by Django 3.0.3 on 2020-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20200522_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='endRepeat',
            field=models.DateField(default=models.DateTimeField(help_text='Enter by when must this task be completed in 24-hour Eastern Time in the following format: YYYY-MM-DD HH:MM:SS', verbose_name='Due Date'), help_text='Enter the last day on which this task should repeat in the following format: YYYY-MM-DD', verbose_name='End repeat date'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Never', help_text='How often should this task repeat?', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Ex', 'Exercise'), ('Leis', 'Leisure'), ('House', 'Household'), ('Pers', 'Personal'), ('Work', 'Work'), ('', 'None')], default='', help_text='Not choosing a category may reduce accuracy', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(help_text='Enter by when must this task be completed in 24-hour Eastern Time in the following format: YYYY-MM-DD HH:MM:SS', verbose_name='Due Date'),
        ),
    ]
