# Generated by Django 3.0.3 on 2020-12-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20200522_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='Start time of this event')),
                ('duration', models.DurationField(verbose_name='Duration of this event')),
            ],
            options={
                'ordering': ['startTime', 'duration'],
            },
        ),
    ]
