# Generated by Django 3.0.3 on 2020-12-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20201219_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(help_text='Enter for how long this event will last in the following format: HH:MM:SS', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(help_text='Enter the time at which this event starts in the following format: YYYY-MM-DD HH:MM:SS', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
