runtime: python37
#env: flex
#entrypoint: gunicorn -b :$PORT webapp.wsgi


# NOTE: MAY NEED TO CHANGE CODE BELOW DEPENDING ON LOCATION OF STATIC DIR

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# # [START libraries]
# libraries:
# - name: crispy_forms
#  version: latest
# # [END libraries]
